/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.46
 * Generated at: 2019-10-04 13:48:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<meta name=\"Generator\" content=\"EditPlus®\">\r\n");
      out.write("\t\t<meta name=\"Author\" content=\"\">\r\n");
      out.write("\t\t<meta name=\"Keywords\" content=\"\">\r\n");
      out.write("\t\t<meta name=\"Description\" content=\"\">\r\n");
      out.write("\t\t<title>join</title>\r\n");
      out.write("\t\t<link href=\"./join.css\" rel=\"stylesheet\" type=\"text/css\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tfunction send(){\r\n");
      out.write("\t\t\t\tvar id_view = document.frm.id_view.value;\r\n");
      out.write("\t\t\t\tvar password = document.frm.password.value;\r\n");
      out.write("\t\t\t\tvar password2 = document.frm.password2.value;\r\n");
      out.write("\t\t\t\tvar email = document.frm.emailAdres.value;\r\n");
      out.write("\t\t\t\tvar tel1 = document.frm.Phone1.value;\r\n");
      out.write("\t\t\t\tvar tel2 = document.frm.Phone2.value;\r\n");
      out.write("\t\t\t\tvar tel3 = document.frm.Phone3.value;\r\n");
      out.write("\t\t\t\tvar tel3 = document.frm.Phone3.value;\r\n");
      out.write("\t\t\t\tvar name = document.frm.name.value;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif(id_view==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"아이디를 입력해주세요\");\r\n");
      out.write("\t\t\t\t\tdocument.frm.id_view.focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t} else if(password==\"\") {\r\n");
      out.write("\t\t\t\t\talert(\"비밀번호를 입력해주세요\");\r\n");
      out.write("\t\t\t\t\tdocument.frm.password.focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t} else if(password2==\"\") {\r\n");
      out.write("\t\t\t\t\talert(\"비밀번호를 확인해주세요\");\r\n");
      out.write("\t\t\t\t\tdocument.frm.password.focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t} else if(name==\"\") {\r\n");
      out.write("\t\t\t\t\talert(\"이름을 입력해주세요.\");\r\n");
      out.write("\t\t\t\t\tdocument.frm.password.focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tif(confirm(\"가입하시겠습니까?\")) {    \t\t\t \r\n");
      out.write("\t\t\t\t\t\tdocument.frm.submit();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar regExp = /[a-z0-9]{2,}@[a-z0-9-]{2,}\\.[a-z0-9]{2,}/i;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif(!regExp.test(email)){\r\n");
      out.write("\t\t\t\t\talert(\"이메일 형식이 일치하지 않습니다.\");\r\n");
      out.write("\t\t\t\t\tdocument.frm.emailAdres.focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar tel1Chk = /^0(2|1[01679])$/;\r\n");
      out.write("\t\t\t\tvar tel2Chk = /^[0-9]{3,}$/;\r\n");
      out.write("\t\t\t\tvar tel3Chk = /^[0-9]{4}$/;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (tel1.value != '') {\r\n");
      out.write("\t\t\t\t\tif (!tel1Chk.test(tel1)){\r\n");
      out.write("\t\t\t\t\t\talert(\"번호형식이 일치하지 않습니다.\");\r\n");
      out.write("\t\t\t\t\t\tdocument.frm.Phone1.focus();\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif (!tel2Chk.test(tel2)){\r\n");
      out.write("\t\t\t\t\t\talert(\"번호형식이 일치하지 않습니다.\");\r\n");
      out.write("\t\t\t\t\t\tdocument.frm.Phone2.focus();\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif (!tel3Chk.test(tel3)){\r\n");
      out.write("\t\t\t\t\t\talert(\"번호형식이 일치하지 않습니다.\");\r\n");
      out.write("\t\t\t\t\t\tdocument.frm.Phone3.focus();\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t<a href=\"../main.jsp\">로고</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"topnavi_ds\">\r\n");
      out.write("\t\t\t<div class=\"topnavi\">  \r\n");
      out.write("\t\t\t\t<a href=\"../intro/intro.jsp\">회사소개</a> |\t\r\n");
      out.write("\t\t\t\t<a href=\"../board/list.jsp\">게시판</a> | \r\n");
      out.write("\t\t\t\t<a href=\"../member/login.jsp\">로그인</a> |\r\n");
      out.write("\t\t\t\t <a href=\"./join.jsp\">회원가입</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"divide\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form name=\"frm\">\r\n");
      out.write("\t\t\t\t<div class=\"modify_user\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr><td colspan=\"4\" height=\"30\">기본정보</td></tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>아이디</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" size=\"20\" maxlength=\"20\" name=\"id_view\" >\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>비밀번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"password\" path=\"password\" name=\"password\" id=\"password\" title=\"비밀번호\" size=\"20\" maxlength=\"20\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>비밀번호 확인</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"password2\" id=\"password2\" title=\"비밀번호확인\" type=\"password\" size=\"20\" maxlength=\"20\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"userNm\" id=\"userNm\" title=\"사용자이름\" type=\"text\" size=\"20\" value=\"\" maxlength=\"60\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>성별</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"gen\" name=\"gen\" title=\"성별\" value=\"남자\">남자\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;&nbsp;<input type=\"radio\" id=\"gen\" name=\"gen\" title=\"성별\" value=\"여자\">여자\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>이메일</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"emailAdres\" id=\"emailAdres\" title=\"이메일주소\" cssClass=\"txaIpt\" size=\"30\" maxlength=\"50\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>연락처</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"Phone1\" id=\"Phone1\" title=\"번호1\" cssClass=\"txaIpt\" size=\"4\" maxlength=\"3\" /> -\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"Phone2\" id=\"Phone2\" title=\"번호2\" cssClass=\"txaIpt\" size=\"5\" maxlength=\"4\" /> -\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"Phone3\" id=\"Phone3\" title=\"번호3\" cssClass=\"txaIpt\" size=\"5\" maxlength=\"4\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"memberPhone\" id=\"memberPhone\" title=\"핸드폰번호\" size=\"20\" maxlength=\"15\" />\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr><td colspan=\"6\" height=\"30\">추가정보</td></tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>소속</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"1\"><input name=\"orgnz\" id=\"orgnz\" title=\"소속\" type=\"text\" size=\"20\" value=\"\" maxlength=\"60\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>직위</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"position\" id=\"position\" title=\"직위\" type=\"text\" size=\"20\" value=\"\" maxlength=\"60\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>최종학력</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"spec\" title=\"최종학력\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">학력선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"초등학교 재학\">초등학교 재학</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"초등학교 졸업\">초등학교 졸업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"중학교 재학\">중학교 재학</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"중학교 졸업\">중학교 졸업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"고등학교 재학\">고등학교 재학</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"고등학교 졸업\">고등학교 졸업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"대학교 재학\">대학교 재학</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"대학교 졸업\">대학교 졸업</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"대학원 재학\">대학원 재학</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>종교</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"religion\" id=\"religion\" title=\"종교\" type=\"text\" size=\"20\" value=\"\" maxlength=\"60\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t<th>결혼여부</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;&nbsp;<input type=\"radio\" name=\"marry\" value=\"미혼\">미혼 \r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;&nbsp;<input type=\"radio\" name=\"marry\" value=\"기혼\">기혼\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>주소</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"zipcode\" size=\"60\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>상세주소</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"addr\" name=\"addr_remain\" size=\"60\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"buttons\" style=\"padding-top:10px;padding-bottom:30px; float:left;\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#LINK\" onclick=\"javascript:send(); return false;\">회원가입</a> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"#LINK\">취소</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
